### ISSUE TITLE
Arabic Release Notes Not being published

### ISSUE THREAD

**Issue by Warhammer4000** [r0adkll/upload-google-play#38] opened 2020-11-13 08:06 UTC
So I have this folder where  I followed this structure
projectDir/
└── whatsNew/
    ├── whatsnew-en-US
    └── whatsnew-ar

After the action has been executed the english notes has been uploaded but not ar. I checked the BCP 47 standard for the code as well.

**Comment by boswelja** [comment] 2022-06-15 01:55
Are you still seeing this issue?

**Comment by boswelja** [comment] 2022-06-15 01:57
Actually, looks like #77 is a duplicate of this and is not limited to Arabic. Closing this to track the isue with more info

**Closed by boswelja** 2022-06-15 01:57 UTC
Labels: bug, question
