### ISSUE TITLE
Random fails with "Error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication "

### ISSUE THREAD

**Issue by crazyhappygame** [r0adkll/upload-google-play#189] opened 2023-09-16 18:17 UTC
**Describe the bug**
From time to time job/step with following error. It succeed after few retries. 
```
Error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

```

**Workflow Step Configuration**

```yml
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ${{ matrix.apps.packageName }}
          releaseFiles: ${{ matrix.apps.releaseFiles }}
          track: internal
```

**Step Debugging**

- [x] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

```
##[debug]Evaluating condition for step: 'Run r0adkll/upload-google-play@v1'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run r0adkll/upload-google-play@v1
##[debug]Loading inputs
##[debug]Evaluating: secrets.SERVICE_ACCOUNT_JSON
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'SERVICE_ACCOUNT_JSON'
##[debug]=> '***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]***'
##[debug]Result: '***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]***'
##[debug]Evaluating: matrix.apps.packageName
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'apps'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'packageName'
##[debug]=> 'com.xxxx.planetdraw'
##[debug]Result: 'com.xxxx.planetdraw'
##[debug]Evaluating: matrix.apps.releaseFiles
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'apps'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'releaseFiles'
##[debug]=> 'artifact/SmartDraw/**/*.apk'
##[debug]Result: 'artifact/SmartDraw/**/*.apk'
##[debug]Loading env
Run r0adkll/upload-google-play@v1
Creating a new Edit for this release
##[debug]This new edit expires at 1694894442
Validating track 'internal'
Uploading artifact/SmartDraw/proj.android/app/build/outputs/apk/release/studio-arm64-v8a-release.apk
##[debug][05558771284423141568, packageName=com.xxxx.planetdraw]: Uploading APK @ artifact/SmartDraw/proj.android/app/build/outputs/apk/release/studio-arm64-v8a-release.apk
Error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
##[debug]Cleaning up service account json file
##[debug]Node Action run completed with exit code 1
##[debug]GOOGLE_APPLICATION_CREDENTIALS='./serviceAccountJson.json'
##[debug]Finishing: Run r0adkll/upload-google-play@v1
```

**Comment by boswelja** [comment] 2023-09-17 01:16
Duplicate of #188

**Closed by boswelja** 2023-09-17 01:16 UTC
Labels: duplicate
