### ISSUE TITLE
The caller does not have permission

### ISSUE THREAD

**Issue by shubhwicked** [r0adkll/upload-google-play#98] opened 2022-03-09 06:00 UTC
I am using r0adkll/upload-google-play@v1.0.15 for releasing my bundle on the play store. It was working fine till now, but suddenly I am getting this error while uploading the bundle to the play store.

```yml
- name: Upload build to playstore
   uses: r0adkll/upload-google-play@v1.0.15
   with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: packageName(our package name)
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal
        inAppUpdatePriority: 5
        whatsNewDirectory: ReleaseNotes/
        mappingFile: app/build/outputs/mapping/release/mapping.txt
```

I am getting this error on github actions
```
##[endgroup***
Creating a new Edit for this release
##[error***The caller does not have permission

```

**Comment by adamdanielczyk** [comment] 2022-05-21 21:46
The error is related to the google service account that's used for the upload (`SERVICE_ACCOUNT_JSON`) - please make sure that it has necessary permissions. See this answer, perhaps it may help: https://github.com/fastlane/fastlane/issues/16164#issuecomment-718319352

**Comment by boswelja** [comment] 2022-06-15 02:01
this is a duplicate of #55 too, closing this

**Closed by boswelja** 2022-06-15 02:01 UTC
Labels: bug
