### ISSUE TITLE
Error: Invalid value at 'track_config.releases[0].status'

### ISSUE THREAD

**Issue by valeriyo** [r0adkll/upload-google-play#127] opened 2022-06-30 23:15 UTC
Why?
```
Creating a new Edit for this release
Validating track 'internal'
Uploading ./artifacts/com.example.app-release.aab
Successfully uploaded 1 artifacts
Adding 1 artifacts to release on 'internal' track
Error: Invalid value at 'track_config.releases[0].status' (type.googleapis.com/google.play.publishingapi.v3.Release.Status), ""
```

```yml
      - uses: r0adkll/upload-google-play@v1
        with:
          track: internal
          packageName: com.example.app
          releaseFiles: ./artifacts/com.example.app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
```

**Comment by valeriyo** [comment] 2022-06-30 23:46
For the record, adding this line fixed it:
```
          status: completed
```
Hopefully this helps someone.

**Comment by skeeping** [comment] 2022-07-05 11:25
thanks @valeriyo it helped me

**Comment by Del-S** [comment] 2022-07-26 21:47
Seems like this is a duplicate of https://github.com/r0adkll/upload-google-play/issues/85 which should be fixed by https://github.com/r0adkll/upload-google-play/pull/87/files. I check the source and the change is in the latest version. But using `uses: r0adkll/upload-google-play@v1` still produces this issue.

Adding `status: completed` helps. Thanks @valeriyo.

**Comment by boswelja** [comment] 2022-09-11 08:04
Yep, please make sure you're pointed to the latest release (NOT v1). There are some pipeline issues that break updating the v1 tag

**Closed by boswelja** 2022-09-11 08:04 UTC
Labels: bug
