### ISSUE TITLE
Unable to find any release file  

### ISSUE THREAD

**Issue by ssepulveda08** [r0adkll/upload-google-play#100] opened 2022-03-31 18:30 UTC
When I try to launch the workflows I get this error: 
Unable to find any release file @ app/build/outputs/bundle/release/app-release.aab

     ` uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          # 3
          packageName: MyPackage
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          status: completed
          mappingFile: mapping.txt`
          

already tried changing releaseFiles with:  ` releaseFiles: app/build/outputs/bundle/release/*.aab` but it doesn't work either

**Comment by markdturner** [comment] 2022-04-12 20:43
This looks the same as #90 and I also have the same problem. From that other issue, I have tried setting the path in absolute and relative terms but no joy.

```yaml
releaseFiles: ./build/app/outputs/apk/release/*.apk'
```
```yaml
releaseFiles: ${{ github.workspace }}/build/app/outputs/apk/release/*.apk'
```

the path is correct as I can use it to add artefacts to the repo in a subsequent step
```yaml
- name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk'
```

**Comment by ssepulveda08** [comment] 2022-04-13 16:20
I struggled a lot with this, in my case the solution was to use the r0adkll/upload-google-play@v1.0.15 version, I share the workflows with you.

    name: Deploy to Play Store
  
    on:
      push:
        branches:
          - master
    
    jobs:
      deploy:
        runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build
        run: ./gradlew build

      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease
          
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          
      - name: Deploy 
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJson: service_account.json
          packageName: MyPackage
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: production
          inAppUpdatePriority: 1`

**Comment by boswelja** [comment] 2022-06-15 01:28
Duplicate of #90, closing

**Closed by boswelja** 2022-06-15 01:28 UTC
Labels: duplicate

**Comment by Skullcan** [comment] 2022-07-28 13:57
If anyone is struggling to setup and getting this error in a React Native project here's my workflow file.

https://gist.github.com/Skullcan/82e7913de667d6fe396fc17303d6ebcf

The trick that did for me was the releaseFiles: ./android/app/build/outputs/bundle/release/app-release.aab.
